<<<<<<< HEAD
buscarcuentas:
  pattern: /buscarcuentas
=======
buscarcuentas:
  pattern: /buscarcuentas
>>>>>>> 30fa032eaa121a2a644bd8fdcc615fe16e877a7d
  defaults: { _controller: BrasaContabilidadBundle:Contabilidad:buscarCuentas}