buscarcuentas:
  pattern: /buscarcuentas
  defaults: { _controller: BrasaContabilidadBundle:Contabilidad:buscarCuentas}
  
brs_ctb_consultas_registros:
    path:     /ctb/consultas/registros/
    defaults: { _controller: BrasaContabilidadBundle:ConsultasRegistros:lista }   
    
brs_ctb_utilidades_intercambio_datos_exportar:
    path:     /ctb/utilidades/intercambio/datos/exportar
    defaults: { _controller: BrasaContabilidadBundle:UtilidadesIntercambioDatos:exportar }
    
# Base

brs_ctb_base_terceros_lista:
    path:     /ctb/base/terceros/lista
    defaults: { _controller: BrasaContabilidadBundle:BaseTercero:lista }
    
brs_ctb_base_terceros_nuevo:
    path:     /ctb/base/terceros/nuevo/{codigoTercero}
    defaults: { _controller: BrasaContabilidadBundle:BaseTercero:nuevo }    