buscarcuentas:
  pattern: /buscarcuentas
  defaults: { _controller: BrasaContabilidadBundle:Contabilidad:buscarCuentas}
  
brs_ctb_consultas_registros:
    path:     /ctb/consultas/registros/
    defaults: { _controller: BrasaContabilidadBundle:ConsultasRegistros:lista }   
    
brs_ctb_utilidades_intercambio_datos_exportar:
    path:     /ctb/utilidades/intercambio/datos/exportar
    defaults: { _controller: BrasaContabilidadBundle:UtilidadesIntercambioDatos:exportar }
    
# Base

brs_ctb_base_terceros_lista:
    path:     /ctb/base/terceros/lista
    defaults: { _controller: BrasaContabilidadBundle:BaseTercero:lista }
    
brs_ctb_base_terceros_nuevo:
    path:     /ctb/base/terceros/nuevo/{codigoTercero}
    defaults: { _controller: BrasaContabilidadBundle:BaseTercero:nuevo } 
    
brs_ctb_base_comprobantes_lista:
    path:     /ctb/base/comprobantes/lista
    defaults: { _controller: BrasaContabilidadBundle:BaseComprobante:lista }
    
brs_ctb_base_comprobantes_nuevo:
    path:     /ctb/base/comprobantes/nuevo/{codigoComprobante}
    defaults: { _controller: BrasaContabilidadBundle:BaseComprobante:nuevo } 
    
brs_ctb_base_cuentas_lista:
    path:     /ctb/base/cuentas/lista
    defaults: { _controller: BrasaContabilidadBundle:BaseCuenta:lista }
    
brs_ctb_base_cuentas_nuevo:
    path:     /ctb/base/cuentas/nuevo/{codigoCuenta}
    defaults: { _controller: BrasaContabilidadBundle:BaseCuenta:nuevo }    
    
# Movimientos

brs_ctb_mov_asientos_lista:
    path:     /ctb/movimientos/asientos/lista
    defaults: { _controller: BrasaContabilidadBundle:Asiento:lista }
    
brs_ctb_mov_asientos_nuevo:
    path:     /ctb/movimientos/asientos/nuevo/{codigoAsiento}
    defaults: { _controller: BrasaContabilidadBundle:Asiento:nuevo } 
    
brs_ctb_mov_asientos_detalle:
    path:     /ctb/movimientos/asientos/detalle/{codigoAsiento}
    defaults: { _controller: BrasaContabilidadBundle:Asiento:detalle } 
    
brs_ctb_mov_asientos_detalle_nuevo:
    path:     /ctb/movimientos/asientos/detalle/nuevo/{codigoAsiento}/{codigoAsientoDetalle}
    defaults: { _controller: BrasaContabilidadBundle:Asiento:detalleNuevo }    