brs_ad_archivos_lista:
   path:     /ad/archivos/lista/{codigoDocumento}/{numero}
   defaults: { _controller: BrasaAdministracionDocumentalBundle:Archivos:lista }
   
brs_ad_archivos_cargar:
   path:     /ad/archivos/cargar/{codigoDocumento}/{numero}
   defaults: { _controller: BrasaAdministracionDocumentalBundle:Archivos:cargar }   

brs_ad_archivos_descargar:
   path:     /ad/archivos/descargar/{codigoArchivo}
   defaults: { _controller: BrasaAdministracionDocumentalBundle:Archivos:descargar } 
   
brs_ad_archivos_enviar:
   path:     /ad/archivos/enviar/{codigoDocumento}/{numero}/{codigoArchivo}
   defaults: { _controller: BrasaAdministracionDocumentalBundle:Archivos:enviar }   