brs_tte_guias_lista:
    path:     /transporte/guias/lista
    defaults: { _controller: BrasaTransporteBundle:Guias:lista }

brs_tte_guias_detalle:
    path:     /transporte/guias/detalle/{codigoGuia}
    defaults: { _controller: BrasaTransporteBundle:Guias:detalle }
    
brs_tte_guias_nuevo:
    path:     /transporte/guias/nuevo/{codigoGuia}
    defaults: { _controller: BrasaTransporteBundle:Guias:nuevo }    

brs_tte_guias_funciones_entregar:
    path:     /transporte/guias/funciones/entregar
    defaults: { _controller: BrasaTransporteBundle:GuiasFunciones:entregar }    
    
brs_tte_guias_funciones_descargar:
    path:     /transporte/guias/funciones/descargar
    defaults: { _controller: BrasaTransporteBundle:GuiasFunciones:descargar }    
    
brs_tte_despachos_lista:
    path:     /transporte/despachos/lista
    defaults: { _controller: BrasaTransporteBundle:Despachos:lista }

brs_tte_despachos_detalle:
    path:     /transporte/despachos/detalle/{codigoDespacho}
    defaults: { _controller: BrasaTransporteBundle:Despachos:detalle }
    
brs_tte_despachos_nuevo:
    path:     /transporte/despachos/nuevo/{codigoDespacho}
    defaults: { _controller: BrasaTransporteBundle:Despachos:nuevo }   

brs_tte_despachos_agregar_guia:
    path:     /transporte/despachos/agregar/guia/{codigoDespacho}
    defaults: { _controller: BrasaTransporteBundle:DespachosAgregarGuia:lista }

brs_tte_facturas_lista:
    path:     /transporte/facturas/lista
    defaults: { _controller: BrasaTransporteBundle:Facturas:lista }    

brs_tte_facturas_nuevo:
    path:     /transporte/facturas/nuevo/{codigoFactura}
    defaults: { _controller: BrasaTransporteBundle:Facturas:nuevo }      
    
#Utilidades    
brs_tte_buscar_conductor:
    pattern:  /transporte/buscar/conductor/
    defaults: { _controller: BrasaTransporteBundle:Busquedas:buscarConductor }     
    
brs_tte_buscar_vehiculo:
    pattern:  /transporte/buscar/vehiculo/
    defaults: { _controller: BrasaTransporteBundle:Busquedas:buscarVehiculo }     
    
brs_tte_buscar_ruta:
    pattern:  /transporte/buscar/ruta/
    defaults: { _controller: BrasaTransporteBundle:Busquedas:buscarRuta }    
          