Brasa\TransporteBundle\Entity\TteGuias:
    properties:
        ctUnidades:
            - GreaterThan:
                value: 0  
                message: Las unidades deben ser mayores a cero
                
        ctPesoReal:
            - GreaterThan:
                value: 0  
                message: El peso real debe ser superior a cero