brasa_transporte:
    resource: "@BrasaTransporteBundle/Resources/config/routing.yml"
    prefix:   /

brasa_cartera:
    resource: "@BrasaCarteraBundle/Resources/config/routing.yml"
    prefix:   /

brasa_contabilidad:
    resource: "@BrasaContabilidadBundle/Resources/config/routing.yml"
    prefix:   /

brasa_tesoreria:
    resource: "@BrasaTesoreriaBundle/Resources/config/routing.yml"
    prefix:   /

brasa_inventario:
    resource: "@BrasaInventarioBundle/Resources/config/routing.yml"
    prefix:   /

brasa_seguridad:
    resource: "@BrasaSeguridadBundle/Resources/config/routing.yml"
    prefix:   /

brasa_general:
    resource: "@BrasaGeneralBundle/Resources/config/routing.yml"
    prefix:   /

