brs_inv_documentos_lista:
    path:     /inventario/documentos/lista/{codigoTipoDocumento}
    defaults: { _controller: BrasaInventarioBundle:Documentos:lista }

brs_inv_movimientos_lista:
    path:     /inventario/movimientos/lista/{codigoDocumento}
    defaults: { _controller: BrasaInventarioBundle:Movimientos:lista }

brs_inv_movimientos_nuevo:
    path:     /inventario/movimientos/nuevo/{codigoDocumento}/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:Movimientos:nuevo }    
    
brs_inv_movimientos_detalle:
    path:     /inventario/movimientos/detalle/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:Movimientos:detalle }       
    
#Consultas
brs_inv_consultas_kardex:
  pattern: /inventario/consultas/kardex
  defaults: { _controller: BrasaInventarioBundle:Consultas:kardex} 
  
brs_inv_consultas_disponibles:
  pattern: /inventario/consultas/disponibles
  defaults: { _controller: BrasaInventarioBundle:Consultas:disponibles}   
  
brs_inv_consultas_inventario_valorizado:
  pattern: /inventario/consultas/inventario/valorizado
  defaults: { _controller: BrasaInventarioBundle:Consultas:inventarioValorizado}  
  requirements:
        id:  \d+   
  
brs_inv_consultas_item:
    path:     /inventario/consutlas/item/{codigoItem}
    defaults: { _controller: BrasaInventarioBundle:Consultas:item } 
        
brs_inv_consultas_existencias:
  pattern: /inventario/consultas/existencias
  defaults: { _controller: BrasaInventarioBundle:Consultas:existencias} 

brs_inv_consultas_movimientos_pendientes:
  pattern: /inventario/consultas/movimientos/pendientes/{codigoDocumentoTipo}
  defaults: { _controller: BrasaInventarioBundle:Movimientos:movimientospendientes} 
  requirements:
        id:  \d+  
        
brs_inv_consultas_movimientos_pendientes_detalles:
  pattern: /inventario/consultas/movimientos/pendientes/detalles/{codigoMovimiento}/{codigoDocumentoTipo}
  defaults: { _controller: BrasaInventarioBundle:Consultas:movimientosPendientesDetalles, codigoMovimiento: 0, codigoDocumentoTipo: 0 } 
  requirements:
        id:  \d+    

#Acciones
brs_inv_movimientos_agregar_item:
    path:     /inventario/movimientos/agregar/item/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:MovimientosAgregarItem:listaItem }    
    
brs_inv_movimientos_agregar_item_documento:
    path:     /inventario/movimientos/agregar/item/documento/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:MovimientosAgregarItem:documentosControlDetalle }    
    
brs_inv_movimientos_agregar_descuento_financiero:
    path:     /inventario/movimientos/agregar/descuento/financiero/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:MovimientosAgregarDescuentoFinanciero:lista }    
    
#Utilidades    
brs_inv_buscar_item:
    pattern:  /inventario/buscar/item/
    defaults: { _controller: BrasaInventarioBundle:Busquedas:buscarItem }         
    
    
#Procesos
brs_inv_procesos_regenerar_kardex:
  pattern: /inventario/procesos/regenerar/kardex
  defaults: { _controller: BrasaInventarioBundle:Procesos:regenerarKardex}     
  
#Base
brs_inv_base_documentos_lista:
    pattern:  /inventario/base/documentos/lista
    defaults: { _controller: BrasaInventarioBundle:Documentos:listaBase }

brs_inv_base_documentos_nuevo:
  pattern: /inventario/base/documentos/nuevo/{codigoDocumentoPk}
  defaults: { _controller: BrasaInventarioBundle:Documentos:nuevo} 
  
brs_inv_base_documentos_detalle:
  pattern: /maestros/inventario/documentos/detalle/{codigoDocumentoPk}
  defaults: { _controller: BrasaInventarioBundle:Documentos:detalle} 
  
brs_inv_base_items_lista:
    pattern:  /maestros/inventario/items/lista
    defaults: { _controller: BrasaInventarioBundle:Items:lista }

brs_inv_base_items_nuevo:
  pattern: /maestros/inventario/items/nuevo/{codigoItemPk}
  defaults: { _controller: BrasaInventarioBundle:Items:nuevo}          

brs_inv_base_items_detalle:
  pattern: /maestros/inventario/items/detalle/{codigoItemPk}
  defaults: { _controller: BrasaInventarioBundle:Items:detalle} 

brs_inv_base_marcas_lista:
    pattern:  /maestros/inventario/marcas/lista
    defaults: { _controller: BrasaInventarioBundle:Marcas:lista }

brs_inv_base_marcas_nuevo:
  pattern: /maestros/inventario/marcas/nuevo/{codigoMarcaPk}
  defaults: { _controller: BrasaInventarioBundle:Marcas:nuevo}              

brs_inv_base_bodegas_lista:
    pattern:  /maestros/inventario/bodegas/lista
    defaults: { _controller: BrasaInventarioBundle:Bodegas:lista }

brs_inv_base_bodegas_nuevo:
  pattern: /maestros/inventario/bodegas/nuevo/{codigoBodegaPk}
  defaults: { _controller: BrasaInventarioBundle:Bodegas:nuevo}              

brs_inv_base_unidadesmedida_lista:
    pattern:  /maestros/inventario/unidadesmedida/lista
    defaults: { _controller: BrasaInventarioBundle:UnidadesMedida:lista }

brs_inv_base_unidadesmedida_nuevo:
  pattern: /maestros/inventario/unidadesmedida/nuevo/{codigoUnidadMedidaPk}
  defaults: { _controller: BrasaInventarioBundle:UnidadesMedida:nuevo} 

brs_inv_base_listas_costos_lista:
    pattern:  /maestros/inventario/listas/costos/lista
    defaults: { _controller: BrasaInventarioBundle:ListasCostos:listar }  
    
brs_inv_base_listas_costos_nuevo:
    pattern:  /maestros/inventario/listas/costos/nuevo{codigoListaCostosPk}
    defaults: { _controller: BrasaInventarioBundle:ListasCostos:nuevo } 
    
brs_inv_base_listas_costos_detalle:
    pattern:  /maestros/inventario/listas/costos/detalle/{codigoListaCostosPk}/
    defaults: { _controller: BrasaInventarioBundle:ListasCostos:detalle }     

brs_inv_base_listas_costos_detalle_nuevo:
    pattern:  /maestros/inventario/listas/costos/detalle/nuevo/{codigoListaCostosPk}/{codigoListaCostosDetallePk}/
    defaults: { _controller: BrasaInventarioBundle:ListasCostos:detalleNuevo }     
      
brs_inv_base_listas_precios_lista:
    pattern:  /maestros/inventario/listas/precios/lista
    defaults: { _controller: BrasaInventarioBundle:ListasPrecios:listar }  
    
brs_inv_base_listas_precios_nuevo:
    pattern:  /maestros/inventario/listas/precios/nuevo{codigoListaPreciosPk}
    defaults: { _controller: BrasaInventarioBundle:ListasPrecios:nuevo } 
    
brs_inv_base_listas_precios_detalle:
    pattern:  /maestros/inventario/listas/precios/detalle/{codigoListaPreciosPk}/
    defaults: { _controller: BrasaInventarioBundle:ListasPrecios:detalle }     

brs_inv_base_listas_precios_detalle_nuevo:
    pattern:  /maestros/inventario/listas/precios/detalle/nuevo/{codigoListaPreciosPk}/{codigoListaPreciosDetallePk}/
    defaults: { _controller: BrasaInventarioBundle:ListasPrecios:detalleNuevo }     