brs_inv_documentos_lista:
    path:     /inventario/documentos/lista/{codigoTipoDocumento}
    defaults: { _controller: BrasaInventarioBundle:Documentos:lista }

brs_inv_movientos_lista:
    path:     /inventario/movimientos/lista/{codigoDocumento}
    defaults: { _controller: BrasaInventarioBundle:Movimientos:lista }

brs_inv_movientos_nuevo:
    path:     /inventario/movimientos/nuevo/{codigoDocumento}/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:Movimientos:nuevo }    
    
brs_inv_movientos_detalle:
    path:     /inventario/movimientos/detalle/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:Movimientos:detalle }    
               
#Consultas
brs_inv_consultas_item:
    path:     /inventario/consutlas/item/{codigoItem}
    defaults: { _controller: BrasaInventarioBundle:Consultas:item }    

#Acciones
brs_inv_movimientos_agregar_item:
    path:     /inventario/movimientos/agregar/item/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:MovimientosAgregarItem:listaItem }    
    
brs_inv_movimientos_agregar_item_documento:
    path:     /inventario/movimientos/agregar/item/documento/{codigoMovimiento}
    defaults: { _controller: BrasaInventarioBundle:Movimientos:detalle }    