brasa_general_inicio:
    path:     /
    defaults: { _controller: BrasaGeneralBundle:Default:index }

brs_gen_base_terceros:
    path:     /general/base/terceros
    defaults: { _controller: BrasaGeneralBundle:BaseTerceros:lista }
    
brs_gen_base_terceros_nuevo:
    path:     /general/base/terceros/nuevo/{codigoTercero}
    defaults: { _controller: BrasaGeneralBundle:BaseTerceros:nuevo }
    
brs_gen_base_bancos:
    path:     /general/base/bancos
    defaults: { _controller: BrasaGeneralBundle:BaseBancos:lista }   
    
brs_gen_base_bancos_nuevo:
    path:     /general/base/bancos/nuevo/{codigoBanco}
    defaults: { _controller: BrasaGeneralBundle:BaseBancos:nuevo }    

brs_gen_base_cuentas:
    path:     /general/base/cuentas
    defaults: { _controller: BrasaGeneralBundle:BaseCuentas:lista }    

brs_gen_base_cuentas_nuevo:
    path:     /general/base/cuentas/nuevo/{codigoCuenta}
    defaults: { _controller: BrasaGeneralBundle:BaseCuentas:nuevo }    
    
brs_gen_configuracion_general:
    path:     /gen/configuracion/general/{codigoConfiguracionPk}
    defaults: { _controller: BrasaGeneralBundle:ConfiguracionGeneral:configuracion }    
    
#Utilidades    
brs_gen_buscar_tercero:
    pattern:  /general/buscar/tercero/{campoCodigo}/{campoNombre}/
    defaults: { _controller: BrasaGeneralBundle:Busquedas:buscarTercero }     

brs_gen_buscar_ciudad:
    pattern:  /general/buscar/ciudad/{campoCodigo}/{campoNombre}/
    defaults: { _controller: BrasaGeneralBundle:Busquedas:buscarCiudad } 
