brasa_general_inicio:
    path:     /
    defaults: { _controller: BrasaGeneralBundle:Default:index }

brs_gen_base_terceros:
    path:     /general/base/terceros
    defaults: { _controller: BrasaGeneralBundle:BaseTerceros:lista }
    
#Utilidades    
brs_gen_buscar_tercero:
    pattern:  /general/buscar/tercero/{campoCodigo}/{campoNombre}/
    defaults: { _controller: BrasaGeneralBundle:Busquedas:buscarTercero }     

brs_gen_buscar_ciudad:
    pattern:  /general/buscar/ciudad/{campoCodigo}/{campoNombre}/
    defaults: { _controller: BrasaGeneralBundle:Busquedas:buscarCiudad } 