brasa_general_inicio:
    path:     /
    defaults: { _controller: BrasaGeneralBundle:Default:index }

brs_gen_base_terceros:
    path:     /general/base/terceros
    defaults: { _controller: BrasaGeneralBundle:BaseTerceros:lista }
    
brs_gen_base_terceros_nuevo:
    path:     /general/base/terceros/nuevo/{codigoTercero}
    defaults: { _controller: BrasaGeneralBundle:BaseTerceros:nuevo }
    
brs_gen_base_bancos:
    path:     /general/base/bancos
    defaults: { _controller: BrasaGeneralBundle:BaseBancos:lista }   
    
brs_gen_base_bancos_nuevo:
    path:     /general/base/bancos/nuevo/{codigoBanco}
    defaults: { _controller: BrasaGeneralBundle:BaseBancos:nuevo } 
    
brs_gen_base_contenido_formato_lista:
   path:     /general/base/contenido/formato/lista/
   defaults: { _controller: BrasaGeneralBundle:BaseContenidoFormato:lista }    
    
brs_gen_base_contenido_formato_nuevo:
   path:     /general/base/contenido/formato/nuevo/{codigoContenidoFormato}
   defaults: { _controller: BrasaGeneralBundle:BaseContenidoFormato:nuevo }    

brs_gen_base_cuentas:
    path:     /general/base/cuentas
    defaults: { _controller: BrasaGeneralBundle:BaseCuentas:lista }    

brs_gen_base_cuentas_nuevo:
    path:     /general/base/cuentas/nuevo/{codigoCuenta}
    defaults: { _controller: BrasaGeneralBundle:BaseCuentas:nuevo }
    
brs_gen_base_asesor:
    path:     /general/base/asesor
    defaults: { _controller: BrasaGeneralBundle:BaseAsesor:lista }   
    
brs_gen_base_asesor_nuevo:
    path:     /general/base/asesor/nuevo/{codigoAsesor}
    defaults: { _controller: BrasaGeneralBundle:BaseAsesor:nuevo }    
    
brs_gen_configuracion_general:
    path:     /gen/configuracion/general/{codigoConfiguracionPk}
    defaults: { _controller: BrasaGeneralBundle:ConfiguracionGeneral:configuracion }    

brs_gen_utilidad_calendario:
    path:     /gen/utilidades/calendario/
    defaults: { _controller: BrasaGeneralBundle:UtilidadCalendario:ver }    

brs_gen_evento_nuevo:
    path:     /gen/evento/nuevo/
    defaults: { _controller: BrasaGeneralBundle:Evento:nuevo }      
    
#Utilidades    
brs_gen_buscar_tercero:
    pattern:  /general/buscar/tercero/{campoCodigo}/{campoNombre}
    defaults: { _controller: BrasaGeneralBundle:BuscarTercero:lista }     

brs_gen_buscar_ciudad:
    pattern:  /general/buscar/ciudad/{campoCodigo}/{campoNombre}/
    defaults: { _controller: BrasaGeneralBundle:Busquedas:buscarCiudad } 
    
brs_gen_borrar_bd:
    pattern:  /general/borrar/bd/
    defaults: { _controller: BrasaGeneralBundle:ConfiguracionGeneral:borrarBD }

brs_gen_mov_tarea_lista:
    pattern:  /general/movimiento/tarea/lista/
    defaults: { _controller: BrasaGeneralBundle:MovimientoTarea:lista } 

brs_gen_mov_tarea_nuevo:
    pattern:  /general/movimiento/tarea/nuevo/{codigoTarea}/
    defaults: { _controller: BrasaGeneralBundle:MovimientoTarea:nuevo } 

#//Gestor de archivos 

brs_gen_utilidad_gestorarchivo:
    pattern:  /general/utilidad/gestorarchivo/{codigoDirectorioPadre}
    defaults: { _controller: BrasaGeneralBundle:Directorio:lista }
    
brs_gen_utilidad_gestorarchivo_directorio_nuevo:
    pattern:  /general/utilidad/gestorarchivo/directorio/nuevo/{codigoDirectorio}/{codigoDirectorioPadre}
    defaults: { _controller: BrasaGeneralBundle:Directorio:nuevoDirectorio }    
    
brs_gen_utilidad_gestorarchivo_cargar_archivo:
    pattern:  /general/utilidad/gestorarchivo/cargar/archivo/{codigoDirectorioPadre}
    defaults: { _controller: BrasaGeneralBundle:Directorio:cargarArchivo } 
    
brs_gen_utilidad_gestorarchivo_descargar_archivo:
    pattern:  /general/utilidad/gestorarchivo/descargar/archivo/{codigoArchivo}
    defaults: { _controller: BrasaGeneralBundle:Directorio:descargarArchivo }    

