brs_rhu_utilidades_pagos_generar_periodo:
    path:     /rhumano/utilidades/pagos/generar/periodo
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPeriodo } 

brs_rhu_utilidades_pagos_generar_pago:
    path:     /rhumano/utilidades/pagos/generar/pago
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPago } 

brs_rhu_utilidades_pagos_generar_pago_resumen:
    path:     /rhumano/utilidades/pagos/generar/pago/resumen/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPagoResumen } 
    
brs_rhu_pagos_adicionales_lista:
    path:     /rhumano/pagos/adicionales/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:lista }     
    
brs_rhu_pagos_adicionales_detalle:
    path:     /rhumano/pagos/adicionales/detalle/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:detalle }         

brs_rhu_pagos_adicionales_agregar_concepto:
    path:     /rhumano/pagos/adicionales/agregar/concepto/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionalesAgregarConcepto:lista }    
    
brs_rhu_creditos_lista:
    path:     /rhumano/creditos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Creditos:lista }
    
brs_rhu_incapacidades_lista:
    path:     /rhumano/incapacidades/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Incapacidades:lista }    

brs_rhu_incapacidades_detalle:
    path:     /rhumano/incapacidades/detalle/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:Incapacidades:detalle }    
    
brs_rhu_pagos_lista:
    path:     /rhumano/pagos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Pagos:lista }     
    
brs_rhu_pagos_detalle:
    path:     /rhumano/pagos/detalle/{codigoPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:Pagos:detalle }    
    
brs_rhu_base_centro_costo:
    path:     /rhumano/base/centrocosto
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseCentroCosto:lista } 
    
    