brs_rhu_utilidades_pagos_generar_periodo:
    path:     /rhumano/utilidades/pagos/generar/periodo
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPeriodo } 

brs_rhu_utilidades_pagos_generar_pago:
    path:     /rhumano/utilidades/pagos/generar/pago
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPago } 

brs_rhu_utilidades_pagos_generar_pago_resumen:
    path:     /rhumano/utilidades/pagos/generar/pago/resumen/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPagoResumen } 
    
brs_rhu_utilidades_pagos_pagar:
    path:     /rhumano/utilidades/pagos/pagar
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:pagar }    
    
brs_rhu_pagos_adicionales_lista:
    path:     /rhumano/pagos/adicionales/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:lista }     
    
brs_rhu_pagos_adicionales_detalle:
    path:     /rhumano/pagos/adicionales/detalle/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:detalle }         

brs_rhu_pagos_adicionales_generarmasivo_lista:
    path:     /rhumano/pagos/adicionales/generarmasivo/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:generarMasivoLista }

brs_rhu_pagos_adicionales_generarmasivo_detalle:
    path:     /rhumano/pagos/adicionales/generarmasivo/detalle/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:generarMasivoDetalle }

brs_rhu_pagos_adicionales_agregar_concepto:
    path:     /rhumano/pagos/adicionales/agregar/concepto/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionalesAgregarConcepto:lista }    

brs_rhu_pagos_adicionales_agregar_incapacidad:
    path:     /rhumano/pagos/adicionales/agregar/incapacidad/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionalesAgregarIncapacidad:nuevo }    

brs_rhu_descuentos_adicionales_lista:
    path:     /rhumano/descuentos/adicionales/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:DescuentosAdicionales:lista }     
    
brs_rhu_descuentos_adicionales_detalle:
    path:     /rhumano/descuentos/adicionales/detalle/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:DescuentosAdicionales:detalle }     
    
brs_rhu_descuentos_adicionales_agregar_concepto:
    path:     /rhumano/descuentos/adicionales/agregar/concepto/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:DescuentosAdicionalesAgregarConcepto:nuevo }    

brs_rhu_descuentos_adicionales_agregar_licencia:
    path:     /rhumano/descuentos/adicionales/agregar/licencia/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:DescuentosAdicionalesAgregarLicencia:nuevo }        

brs_rhu_descuentos_adicionales_generarmasivo_detalle:
    path:     /rhumano/descuentos/adicionales/generarmasivo/detalle/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:DescuentosAdicionales:generarMasivoDetalle }    
    
brs_rhu_creditos_lista:
    path:     /rhumano/creditos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Creditos:lista }       

brs_rhu_creditos_nuevo:
    path:     /rhumano/creditos/nuevo/{codigoCredito}
    defaults: { _controller: BrasaRecursoHumanoBundle:Creditos:nuevo }     
    
brs_rhu_pagos_lista:
    path:     /rhumano/pagos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Pagos:lista }     
    
brs_rhu_pagos_detalle:
    path:     /rhumano/pagos/detalle/{codigoPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:Pagos:detalle }    
    
brs_rhu_base_centros_costos_lista:
    path:     /rhumano/base/centroscostos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseCentroCosto:lista } 

brs_rhu_base_centros_costos_nuevo:
    path:     /rhumano/base/centroscostos/nuevo/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseCentroCosto:nuevo }    
    
brs_rhu_base_empleados_lista:
    path:     /rhumano/base/empleados/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseEmpleado:lista }     
    
brs_rhu_base_empleados_detalles:
    path:     /rhumano/base/empleados/detalles/{codigoEmpleado}
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseEmpleado:detalle }    
    
brs_rhu_base_empleados_nuevo:
    path:     /rhumano/base/empleados/nuevo/{codigoEmpleado}
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseEmpleado:nuevo }     
    
brs_rhu_contratos_nuevo:
    path:     /rhumano/contratos/nuevo/{codigoContrato}{codigoEmpleado}
    defaults: { _controller: BrasaRecursoHumanoBundle:Contratos:nuevo }    
    
brs_rhu_facturas_lista:
    path:     /rhumano/facturas/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Facturas:lista }    
    
brs_rhu_facturas_nuevo:
    path:     /rhumano/facturas/nuevo/{codigoFactura}
    defaults: { _controller: BrasaRecursoHumanoBundle:Facturas:nuevo }        
    
brs_rhu_facturas_detalle:
    path:     /rhumano/facturas/detalle/{codigoFactura}
    defaults: { _controller: BrasaRecursoHumanoBundle:Facturas:detalle }    

brs_rhu_facturas_agregar_pago:
    path:     /rhumano/facturas/agregarpago/{codigoFactura}
    defaults: { _controller: BrasaRecursoHumanoBundle:FacturasAgregarPago:lista }        