brs_rhu_inicio:
    path:     /rhu/inicio   
    defaults: { _controller: BrasaRecursoHumanoBundle:Default:inicio }

brs_rhu_como_iniciar:
    path:     /rhu/como/iniciar   
    defaults: { _controller: BrasaRecursoHumanoBundle:Default:comoIniciar }                                                                                 
    
brs_rhu_pagos_adicionales_lista:
    path:     /rhu/pagos/adicionales/lista/{modalidad}/{periodo}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:lista }     

brs_rhu_pagos_adicionales_lista_fecha:
    path:     /rhu/pagos/adicionales/fecha/lista/{modalidad}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:listaFecha }     
    
brs_rhu_pagos_adicionales_detalle:
    path:     /rhu/pagos/adicionales/detalle/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:detalle }         

brs_rhu_pagos_adicionales_generarmasivo_lista:
    path:     /rhu/pagos/adicionales/generarmasivo/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:generarMasivoLista }

brs_rhu_pagos_adicionales_generarmasivo_suplementario_detalle:
    path:     /rhu/pagos/adicionales/generarmasivo/suplementario/detalle/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:generarMasivoSuplementarioDetalle }
    
brs_rhu_pagos_adicionales_agregar_valoradicionaleditar:
    path:     /rhu/pagos/adicionales/agregar/valoradicionaleditar/{tipo}/{codigoPagoAdicional}/{modalidad}/{periodo}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionalesAgregar:valorAdicionalEditar}    
    
brs_rhu_pagos_adicionales_agregar_valoradicional:
    path:     /rhu/pagos/adicionales/agregar/valoradicional/{tipo}/{modalidad}/{periodo}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionalesAgregar:valorAdicional }                                                                
                               
brs_rhu_pagos_lista:
    path:     /rhu/pagos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Pagos:lista }     
    
brs_rhu_pagos_detalle:
    path:     /rhu/pagos/detalle/{codigoPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:Pagos:detalle }    

brs_rhu_programaciones_pago_lista:
    path:     /rhu/programaciones/pago/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:ProgramacionesPago:lista }     
    
brs_rhu_programaciones_pago_detalle:
    path:     /rhu/programaciones/pago/detalle/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:ProgramacionesPago:detalle } 

brs_rhu_programaciones_pago_detalle_prima:
    path:     /rhu/programaciones/pago/detalle/prima/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:ProgramacionesPago:detallePrima }         

brs_rhu_programaciones_pago_nuevo:
    path:     /rhu/programaciones/pago/nuevo
    defaults: { _controller: BrasaRecursoHumanoBundle:ProgramacionesPago:nuevo }     

brs_rhu_programaciones_pago_inconsistencias:
    path:     /rhu/programaciones/pago/inconsistencias/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:ProgramacionesPago:inconsistencias }         

brs_rhu_programaciones_pago_agregar_empleado:
    path:     /rhu/programaciones/pago/agregar/empleado/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:ProgramacionesPago:agregarEmpleado }     

brs_rhu_programaciones_pago_cargar_soporte_turno:
    path:     /rhu/programaciones/pago/cargar/soporte/turno/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:ProgramacionesPagoCargarSoporteTurno:cargar }

brs_rhu_programaciones_pago_cargar_soporte_horario:
    path:     /rhu/programaciones/pago/cargar/soporte/horario/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:ProgramacionesPagoCargarSoporteHorario:cargar }                                                                                     
   
brs_rhu_examen_listar:
   path:     /rhu/examen/listar
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:lista } 
   
brs_rhu_examen_nuevo:
   path:     /rhu/examen/nuevo/{codigoExamen}
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:nuevo }

brs_rhu_examen_nuevo_control:
   path:     /rhu/examen/nuevo/control/{codigoExamen}
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:nuevoControl }   
   
brs_rhu_examen_detalle:
   path:     /rhu/examen/detalle/{codigoExamen}
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:detalle }
   
brs_rhu_examen_detalle_nuevo:
   path:     /rhu/examen/detalle/nuevo/{codigoExamen}
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:detalleNuevo }   

brs_rhu_examen_detalle_nuevo_comentario:
   path:     /rhu/examen/detalle/nuevo/comentario/{codigoExamenDetalle}
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:detalleNuevoComentario }
   
brs_rhu_examen_restriccion_medica_editar:
    path:     /rhu/examen/restriccion/medica/editar/{codigoExamen}/{codigoRestriccionMedica}
    defaults: { _controller: BrasaRecursoHumanoBundle:Examen:editarRestriccionMedica } 
    
brs_rhu_examen_restriccion_medica_agregar:
    path:     /rhu/examen/restriccion/medica/agregar/{codigoExamen}/{codigoRestriccionMedica}
    defaults: { _controller: BrasaRecursoHumanoBundle:Examen:agregarRestriccionMedica }
    
brs_rhu_examen_restriccion_medica_detalle:
    path:     /rhu/examen/restriccion/medica/detalle/{codigoRestriccionMedica}
    defaults: { _controller: BrasaRecursoHumanoBundle:Examen:detalleRestriccionMedica }                                                                
    
brs_rhu_pago_examen_lista:
    path:     /rhu/pago/examen/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:PagoExamen:lista}

brs_rhu_pago_examen_nuevo:
    path:     /rhu/pago/examen/nuevo/{codigoPagoExamen}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagoExamen:nuevo}

brs_rhu_pago_examen_detalle:
    path:     /rhu/pago/examen/detalle/{codigoPagoExamen}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagoExamen:detalle}
    
brs_rhu_pago_examen_detalle_nuevo:
    path:     /rhu/pago/examen/detalle/nuevo/{codigoPagoExamen}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagoExamen:detalleNuevo}                           
       
brs_rhu_configuracion_nomina:
    path:     /rhu/configuracion/{codigoConfiguracionPk}
    defaults: { _controller: BrasaRecursoHumanoBundle:Configuracion:configuracion }                                             
    
brs_rhu_buscar_empleado:
    pattern:  /rhu/buscar/empleado
    defaults: { _controller: BrasaRecursoHumanoBundle:BuscarEmpleado:lista }
    
brs_rhu_buscar_visitante:
    pattern:  /rhu/buscar/visitante
    defaults: { _controller: BrasaRecursoHumanoBundle:BuscarVisitante:lista }    
       