brs_rhu_credito_detalle:
    path:     /rhumano/creditos/detalle/{codigoCreditoPk}
    defaults: { _controller: BrasaRecursoHumanoBundle:Creditos:detalle }
    
brs_rhu_credito_nuevo_detalle:
    path:     /rhumano/creditos/detalle/nuevo/{codigoCreditoPk}
    defaults: { _controller: BrasaRecursoHumanoBundle:Creditos:nuevoDetalle }    

brs_rhu_base_creditotipo_listar:
   path:     /rhumano/base/creditotipo/listar
   defaults: { _controller: BrasaRecursoHumanoBundle:BaseCreditoTipo:listar }
   
brs_rhu_base_creditotipo_nuevo:
   path:     /rhumano/base/creditotipo/nuevo/{codigoCreditoTipoPk}
   defaults: { _controller: BrasaRecursoHumanoBundle:BaseCreditoTipo:nuevo }

brs_rhu_utilidades_pagos_generar_periodo:
    path:     /rhumano/utilidades/pagos/generar/periodo
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPeriodo } 

brs_rhu_utilidades_pagos_generar_pago:
    path:     /rhumano/utilidades/pagos/generar/pago
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPago } 

brs_rhu_utilidades_pagos_generar_pago_resumen:
    path:     /rhumano/utilidades/pagos/generar/pago/resumen/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:generarPagoResumen } 

brs_rhu_utilidades_pagos_generar_pago_resumen_agregarempleado:
    path:     /rhumano/utilidades/pagos/generar/pago/resumen/agregarempleado/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:agregarEmpleado }     

brs_rhu_utilidades_pagos_cargar_tiempo_sede:
    path:     /rhumano/utilidades/pagos/cargar/tiempo/sede/{codigoProgramacionPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesCargarTiempoSedes:cargar }         
    
brs_rhu_utilidades_pagos_pagar:
    path:     /rhumano/utilidades/pagos/pagar
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesPagos:pagar }  
    
brs_rhu_utilidades_notificaciones_cierreprogramacionpago:
    path:     /rhumano/utilidades/notificaciones/cierreprogramacionpago
    defaults: { _controller: BrasaRecursoHumanoBundle:UtilidadesNotificaciones:cierreProgramacionPago }    
    
brs_rhu_pagos_adicionales_lista:
    path:     /rhumano/pagos/adicionales/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:lista }     
    
brs_rhu_pagos_adicionales_detalle:
    path:     /rhumano/pagos/adicionales/detalle/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:detalle }         

brs_rhu_pagos_adicionales_generarmasivo_lista:
    path:     /rhumano/pagos/adicionales/generarmasivo/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:generarMasivoLista }

brs_rhu_pagos_adicionales_generarmasivo_suplementario_detalle:
    path:     /rhumano/pagos/adicionales/generarmasivo/suplementario/detalle/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionales:generarMasivoSuplementarioDetalle }

brs_rhu_pagos_adicionales_agregar_tiempo:
    path:     /rhumano/pagos/adicionales/agregar/tiempo/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionalesAgregar:tiempo }    

brs_rhu_pagos_adicionales_agregar_valor:
    path:     /rhumano/pagos/adicionales/agregar/valor/{codigoCentroCosto}/{tipo}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagosAdicionalesAgregar:valor }    

brs_rhu_liquidaciones_lista:
    path:     /rhumano/liquidaciones/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Liquidaciones:lista }

brs_rhu_liquidaciones_detalle:
    path:     /rhumano/liquidaciones/detalle/{codigoLiquidacion}
    defaults: { _controller: BrasaRecursoHumanoBundle:Liquidaciones:detalle } 

brs_rhu_incapacidades_lista:
    path:     /rhumano/incapacidades/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Incapacidades:lista }    

brs_rhu_incapacidades_nuevo:
    path:     /rhumano/incapacidades/nuevo/{codigoCentroCosto}/{codigoEmpleado}/{codigoIncapacidad}
    defaults: { _controller: BrasaRecursoHumanoBundle:Incapacidades:nuevo }    

brs_rhu_licencias_nuevo:
    path:     /rhumano/licencias/nuevo/{codigoCentroCosto}/{codigoEmpleado}
    defaults: { _controller: BrasaRecursoHumanoBundle:Licencias:nuevo }     
    
brs_rhu_creditos_lista:
    path:     /rhumano/creditos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Creditos:lista }       

brs_rhu_creditos_nuevo:
    path:     /rhumano/creditos/nuevo/{codigoCredito}/{codigoEmpleado}
    defaults: { _controller: BrasaRecursoHumanoBundle:Creditos:nuevo }     
    
brs_rhu_pagos_lista:
    path:     /rhumano/pagos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Pagos:lista }     
    
brs_rhu_pagos_detalle:
    path:     /rhumano/pagos/detalle/{codigoPago}
    defaults: { _controller: BrasaRecursoHumanoBundle:Pagos:detalle }    
    
brs_rhu_base_centros_costos_lista:
    path:     /rhumano/base/centroscostos/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseCentroCosto:lista } 

brs_rhu_base_centros_costos_nuevo:
    path:     /rhumano/base/centroscostos/nuevo/{codigoCentroCosto}
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseCentroCosto:nuevo }    
    
brs_rhu_base_empleados_lista:
    path:     /rhumano/base/empleados/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseEmpleado:lista }     
    
brs_rhu_base_empleados_detalles:
    path:     /rhumano/base/empleados/detalles/{codigoEmpleado}
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseEmpleado:detalle }    
    
brs_rhu_base_empleados_nuevo:
    path:     /rhumano/base/empleados/nuevo/{codigoEmpleado}/{codigoSeleccion}
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseEmpleado:nuevo }     

brs_rhu_base_empleados_nuevo_enlazar:
    path:     /rhumano/base/empleados/nuevo/enlazar/
    defaults: { _controller: BrasaRecursoHumanoBundle:BaseEmpleado:enlazar }     

brs_rhu_base_contratos_lista:
    path:     /rhumano/base/contratos/lista/
    defaults: { _controller: BrasaRecursoHumanoBundle:Contratos:lista }    

brs_rhu_base_contratos_detalles:
    path:     /rhumano/base/contratos/detalle/{codigoContrato}
    defaults: { _controller: BrasaRecursoHumanoBundle:Contratos:detalle }        
    
brs_rhu_contratos_nuevo:
    path:     /rhumano/contratos/nuevo/{codigoContrato}/{codigoEmpleado}
    defaults: { _controller: BrasaRecursoHumanoBundle:Contratos:nuevo }    

brs_rhu_contratos_terminar:
    path:     /rhumano/contratos/terminar/{codigoContrato}
    defaults: { _controller: BrasaRecursoHumanoBundle:Contratos:terminar }        
    
brs_rhu_facturas_lista:
    path:     /rhumano/facturas/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Facturas:lista }    
    
brs_rhu_facturas_nuevo:
    path:     /rhumano/facturas/nuevo/{codigoFactura}
    defaults: { _controller: BrasaRecursoHumanoBundle:Facturas:nuevo }        
    
brs_rhu_facturas_detalle:
    path:     /rhumano/facturas/detalle/{codigoFactura}
    defaults: { _controller: BrasaRecursoHumanoBundle:Facturas:detalle }    

brs_rhu_facturas_agregar_pago:
    path:     /rhumano/facturas/agregarpago/{codigoFactura}
    defaults: { _controller: BrasaRecursoHumanoBundle:FacturasAgregarPago:lista }        

brs_rhu_base_salud_listar:
   path:     /rhumano/base/salud/listar
   defaults: { _controller: BrasaRecursoHumanoBundle:BaseSalud:listar }
   
brs_rhu_base_salud_nuevo:
   path:     /rhumano/base/salud/nuevo/{codigoEntidadSaludPk}
   defaults: { _controller: BrasaRecursoHumanoBundle:BaseSalud:nuevo }
   
brs_rhu_examen_listar:
   path:     /rhumano/examen/listar
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:lista } 
   
brs_rhu_examen_nuevo:
   path:     /rhumano/examen/nuevo/{codigoExamen}
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:nuevo }
   
brs_rhu_examen_detalle:
   path:     /rhumano/examen/detalle/{codigoExamen}
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:detalle }
   
brs_rhu_examen_detalle_nuevo:
   path:     /rhumano/examen/detalle/nuevo/{codigoExamen}
   defaults: { _controller: BrasaRecursoHumanoBundle:Examen:detallenuevo }   
   
brs_rhu_base_entidadexamen_listar:
   path:     /rhumano/base/entidadexamen/listar
   defaults: { _controller: BrasaRecursoHumanoBundle:BaseEntidadExamen:listar }
   
brs_rhu_base_entidadexamen_nuevo:
   path:     /rhumano/base/entidadexamen/nuevo/{codigoEntidadExamenPk}
   defaults: { _controller: BrasaRecursoHumanoBundle:BaseEntidadExamen:nuevo }
   
brs_rhu_base_examentipo_listar:      
   path:     /rhumano/base/examentipo/listar
   defaults: { _controller: BrasaRecursoHumanoBundle:BaseExamenTipo:listar }
   
brs_rhu_base_examentipo_nuevo:
   path:     /rhumano/base/examentipo/nuevo/{codigoExamenTipoPk}
   defaults: { _controller: BrasaRecursoHumanoBundle:BaseExamenTipo:nuevo }   

brs_rhu_base_pension_listar:
   path:     /rhumano/base/pension/listar
   defaults: { _controller: BrasaRecursoHumanoBundle:BasePension:listar }
   
brs_rhu_base_pension_nuevo:
   path:     /rhumano/base/pension/nuevo/{codigoEntidadPensionPk}
   defaults: { _controller: BrasaRecursoHumanoBundle:BasePension:nuevo }    

brs_rhu_seleccion_lista:
    path:     /rhumano/seleccion/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:Seleccion:lista }         
    
brs_rhu_seleccion_nuevo:
    path:     /rhumano/seleccion/nuevo/{codigoSeleccion}
    defaults: { _controller: BrasaRecursoHumanoBundle:Seleccion:nuevo } 

brs_rhu_seleccion_agregar_referencia:
    path:     /rhumano/seleccion/agregar/referencia/{codigoSeleccion}
    defaults: { _controller: BrasaRecursoHumanoBundle:Seleccion:agregarReferencia } 

brs_rhu_seleccion_agregar_prueba:
    path:     /rhumano/seleccion/agregar/prueba/{codigoSeleccion}
    defaults: { _controller: BrasaRecursoHumanoBundle:Seleccion:agregarPrueba }

brs_rhu_seleccion_detalle:
    path:     /rhumano/seleccion/detalle/{codigoSeleccion}
    defaults: { _controller: BrasaRecursoHumanoBundle:Seleccion:detalle }     
    
brs_rhu_selecciongrupo_lista:
    path:     /rhumano/selecciongrupo/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:SeleccionGrupo:lista }
    
brs_rhu_selecciongrupo_nuevo:
    path:     /rhumano/selecciongrupo/nuevo/{codigoSeleccionGrupo}
    defaults: { _controller: BrasaRecursoHumanoBundle:SeleccionGrupo:nuevo }     
    
brs_rhu_selecciongrupo_detalle:
    path:     /rhumano/selecciongrupo/detalle/{codigoSeleccionGrupo}
    defaults: { _controller: BrasaRecursoHumanoBundle:SeleccionGrupo:detalle }    

brs_rhu_ss_periodo_lista:
    path:     /rhumano/seguridadsocial/periodo/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:SeguridadSocialPeriodos:lista }     
    
brs_rhu_consultas_costos_general:    
    path:     /rhumano/consultas/costos/general
    defaults: { _controller: BrasaRecursoHumanoBundle:Consultas:costosGeneral }
    
brs_rhu_pago_examen_lista:
    path:     /rhumano/pago/examen/lista
    defaults: { _controller: BrasaRecursoHumanoBundle:PagoExamen:lista}

brs_rhu_pago_examen_nuevo:
    path:     /rhumano/pago/examen/nuevo/{codigoPagoExamen}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagoExamen:nuevo}

brs_rhu_pago_examen_detalle:
    path:     /rhumano/pago/examen/detalle/{codigoPagoExamen}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagoExamen:detalle}
    
brs_rhu_pago_examen_detalle_nuevo:
    path:     /rhumano/pago/examen/detalle/nuevo/{codigoPagoExamen}
    defaults: { _controller: BrasaRecursoHumanoBundle:PagoExamen:detalleNuevo}    