brs_log_guias_lista:
    path:     /logistica/guias/lista
    defaults: { _controller: BrasaLogisticaBundle:Guias:lista }

brs_log_guias_detalle:
    path:     /logistica/guias/detalle/{codigoGuia}
    defaults: { _controller: BrasaLogisticaBundle:Guias:detalle }
    
brs_log_guias_nuevo:
    path:     /logistica/guias/nuevo/{codigoGuia}
    defaults: { _controller: BrasaLogisticaBundle:Guias:nuevo }    

brs_log_guias_funciones_entregar:
    path:     /logistica/guias/funciones/entregar
    defaults: { _controller: BrasaLogisticaBundle:GuiasFunciones:entregar }    
    
brs_log_guias_funciones_descargar:
    path:     /logistica/guias/funciones/descargar
    defaults: { _controller: BrasaLogisticaBundle:GuiasFunciones:descargar }    
    
brs_log_despachos_lista:
    path:     /logistica/despachos/lista
    defaults: { _controller: BrasaLogisticaBundle:Despachos:lista }

brs_log_despachos_detalle:
    path:     /logistica/despachos/detalle/{codigoDespacho}
    defaults: { _controller: BrasaLogisticaBundle:Despachos:detalle }
    
brs_log_despachos_nuevo:
    path:     /logistica/despachos/nuevo/{codigoDespacho}
    defaults: { _controller: BrasaLogisticaBundle:Despachos:nuevo }   

brs_log_despachos_agregar_guia:
    path:     /logistica/despachos/agregar/guia/{codigoDespacho}
    defaults: { _controller: BrasaLogisticaBundle:DespachosAgregarGuia:lista }

brs_log_facturas_lista:
    path:     /logistica/facturas/lista
    defaults: { _controller: BrasaLogisticaBundle:Facturas:lista }    

brs_log_facturas_nuevo:
    path:     /logistica/facturas/nuevo/{codigoFactura}
    defaults: { _controller: BrasaLogisticaBundle:Facturas:nuevo }      
    
#Utilidades    
brs_log_buscar_conductor:
    pattern:  /logistica/buscar/conductor/
    defaults: { _controller: BrasaLogisticaBundle:Busquedas:buscarConductor }     
    
brs_log_buscar_vehiculo:
    pattern:  /logistica/buscar/vehiculo/
    defaults: { _controller: BrasaLogisticaBundle:Busquedas:buscarVehiculo }     
    
brs_log_buscar_ruta:
    pattern:  /logistica/buscar/ruta/
    defaults: { _controller: BrasaLogisticaBundle:Busquedas:buscarRuta }    
          