brs_tur_base_turno_lista:
    path:     /tur/base/turno/lista
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:lista }     
    
brs_tur_base_turno_detalle:
    path:     /tur/base/turno/detalle/{codigoTurno}
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:detalle }    
    
brs_tur_base_turno_nuevo:
    path:     /tur/base/turno/nuevo/{codigoTurno}
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:nuevo }

brs_tur_base_turno_detalle_nuevo:
   path:     /tur/base/turno/detalle/nuevo/{codigoTurno}/{codigoTurnoDetalle}
   defaults: { _controller: BrasaTurnoBundle:BaseTurno:detalleNuevo }

brs_tur_base_recurso_lista:
    path:     /tur/base/recurso/lista
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:lista }     
    
brs_tur_base_recurso_detalle:
    path:     /tur/base/recurso/detalle/{codigoRecurso}
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:detalle }    
    
brs_tur_base_recurso_nuevo:
    path:     /tur/base/recurso/nuevo/{codigoRecurso}
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:nuevo }

brs_tur_base_cliente_lista:
    path:     /tur/base/cliente/lista
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:lista }     
    
brs_tur_base_cliente_detalle:
    path:     /tur/base/cliente/detalle/{codigoCliente}
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:detalle }    
    
brs_tur_base_cliente_nuevo:
    path:     /tur/base/cliente/nuevo/{codigoCliente}
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:nuevo }

brs_tur_base_cliente_puesto_nuevo:
    path:     /tur/base/cliente/puesto/nuevo/{codigoCliente}
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:puestoNuevo }    

brs_tur_base_plantilla_lista:
    path:     /tur/base/plantilla/lista
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:lista }     
    
brs_tur_base_plantilla_detalle:
    path:     /tur/base/plantilla/detalle/{codigoPlantilla}
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:detalle }    
    
brs_tur_base_plantilla_nuevo:
    path:     /tur/base/plantilla/nuevo/{codigoPlantilla}
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:nuevo }

brs_tur_base_plantilla_detalle_nuevo:
   path:     /tur/base/plantilla/detalle/nuevo/{codigoPlantilla}/{codigoPlantillaDetalle}
   defaults: { _controller: BrasaTurnoBundle:BasePlantilla:detalleNuevo } 

brs_tur_programacion_lista:
   path:     /tur/programacion/lista
   defaults: { _controller: BrasaTurnoBundle:MovimientoProgramacion:lista } 
   
brs_tur_programacion_nuevo:
   path:     /tur/programacion/nuevo/{codigoProgramacion}
   defaults: { _controller: BrasaTurnoBundle:MovimientoProgramacion:nuevo }

brs_tur_programacion_detalle:
   path:     /tur/programacion/detalle/{codigoProgramacion}
   defaults: { _controller: BrasaTurnoBundle:MovimientoProgramacion:detalle }
   
brs_tur_programacion_detalle_nuevo:
   path:     /tur/programacion/detalle/nuevo/{codigoProgramacion}/{codigoProgramacionDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoProgramacion:detalleNuevo }   

brs_tur_cotizacion_lista:
   path:     /tur/cotizacion/lista
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:lista } 
   
brs_tur_cotizacion_nuevo:
   path:     /tur/cotizacion/nuevo/{codigoCotizacion}
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:nuevo }

brs_tur_cotizacion_detalle:
   path:     /tur/cotizacion/detalle/{codigoCotizacion}
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:detalle }
   
brs_tur_cotizacion_detalle_nuevo:
   path:     /tur/cotizacion/detalle/nuevo/{codigoCotizacion}/{codigoCotizacionDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:detalleNuevo }    

brs_tur_cotizacion_otro_nuevo:
   path:     /tur/cotizacion/otro/nuevo/{codigoCotizacion}/{codigoCotizacionOtro}
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:otroNuevo }       
   
brs_tur_pedido_lista:
   path:     /tur/pedido/lista
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:lista } 
   
brs_tur_pedido_nuevo:
   path:     /tur/pedido/nuevo/{codigoPedido}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:nuevo }

brs_tur_pedido_detalle:
   path:     /tur/pedido/detalle/{codigoPedido}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalle }
   
brs_tur_pedido_detalle_nuevo:
   path:     /tur/pedido/detalle/nuevo/{codigoPedido}/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalleNuevo }     
   
brs_tur_pedido_detalle_nuevo_cotizacion:
   path:     /tur/pedido/detalle/nuevo/cotizacion/{codigoPedido}/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalleNuevoCotizacion }   

brs_tur_pedido_detalle_recurso:
   path:     /tur/pedido/detalle/recurso/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:recurso }

brs_tur_factura_lista:
   path:     /tur/factura/lista
   defaults: { _controller: BrasaTurnoBundle:MovimientoFactura:lista } 
   
brs_tur_factura_nuevo:
   path:     /tur/factura/nuevo/{codigoFactura}
   defaults: { _controller: BrasaTurnoBundle:MovimientoFactura:nuevo }

brs_tur_factura_detalle:
   path:     /tur/factura/detalle/{codigoFactura}
   defaults: { _controller: BrasaTurnoBundle:MovimientoFactura:detalle }
   
brs_tur_factura_detalle_nuevo:
   path:     /tur/factura/detalle/nuevo/{codigoFactura}/{codigoFacturaDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoFactura:detalleNuevo }            
    
brs_tur_consultas_pedidos_pendientes_programar:    
    path:     /tur/consultas/pedidos/pendientes/programar
    defaults: { _controller: BrasaTurnoBundle:ConsultasPedidosPendientesProgramar:lista }     

brs_tur_consultas_programaciones_detalles:    
    path:     /tur/consultas/programaciones/detalles
    defaults: { _controller: BrasaTurnoBundle:ConsultasProgramacionesDetalles:lista }         

brs_tur_consultas_recursos_programaciones:    
    path:     /tur/consultas/recursos/programaciones
    defaults: { _controller: BrasaTurnoBundle:ConsultasRecursosProgramaciones:lista }     
    
brs_tur_proceso_generar_soporte_pago:
    path:     /tur/proceso/generar/soporte/pago
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarSoportePago:generar }                  
    
brs_tur_proceso_generar_programacion_lista:
    path:     /tur/proceso/generar/programacion/lista
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarProgramacion:lista }         
    
brs_tur_proceso_generar_pedido_lista:
    path:     /tur/proceso/generar/pedido/lista
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarPedido:lista }             
    
brs_tur_utilidad_aplicar_novedad:    
    path:     /tur/utilidad/aplicar/novedad
    defaults: { _controller: BrasaTurnoBundle:UtilidadAplicarNovedad:lista }     
    
brs_tur_buscar_cliente:
    pattern:  /tur/buscar/cliente/{campoCodigo}/{campoNombre}
    defaults: { _controller: BrasaTurnoBundle:BuscarCliente:lista }     
    
brs_tur_buscar_recurso:
    pattern:  /turno/buscar/recurso/{campoCodigo}/{campoNombre}
    defaults: { _controller: BrasaTurnoBundle:BuscarRecurso:buscar }    

brs_tur_buscar_recurso2:
    pattern:  /turno/buscar/recurso/{campoCodigo}
    defaults: { _controller: BrasaTurnoBundle:BuscarRecurso:buscar2 }
    
brs_tur_buscar_puesto:
    pattern:  /turno/buscar/puesto/{campoCodigo}/{codigoCliente}
    defaults: { _controller: BrasaTurnoBundle:BuscarPuesto:lista }    