brs_tur_base_recurso_lista:
    path:     /tur/base/recurso/lista
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:lista }     
    
brs_tur_base_recurso_detalle:
    path:     /tur/base/recurso/detalle/{codigoRecurso}
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:detalle }    
    
brs_tur_base_recurso_nuevo:
    path:     /tur/base/recurso/nuevo/{codigoRecurso}/{codigoEmpleado}
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:nuevo }

brs_tur_base_recurso_nuevo_enlazar:
    path:     /tur/base/recurso/nuevo/enlazar/
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:enlazar } 

brs_tur_base_concepto_servicio_lista:
    path:     /tur/base/concepto/servicio/lista
    defaults: { _controller: BrasaTurnoBundle:BaseConceptoServicio:lista }          
    
brs_tur_base_concepto_servicio_nuevo:
    path:     /tur/base/concepto/servicio/nuevo/{codigoConceptoServicio}
    defaults: { _controller: BrasaTurnoBundle:BaseConceptoServicio:nuevo }               

brs_tur_base_prospecto_lista:
    path:     /tur/base/prospecto/lista
    defaults: { _controller: BrasaTurnoBundle:BaseProspecto:lista }            
    
brs_tur_base_prospecto_nuevo:
    path:     /tur/base/prospecto/nuevo/{codigoProspecto}
    defaults: { _controller: BrasaTurnoBundle:BaseProspecto:nuevo }

brs_tur_base_plantilla_lista:
    path:     /tur/base/plantilla/lista
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:lista }     
    
brs_tur_base_plantilla_detalle:
    path:     /tur/base/plantilla/detalle/{codigoPlantilla}
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:detalle }    
    
brs_tur_base_plantilla_nuevo:
    path:     /tur/base/plantilla/nuevo/{codigoPlantilla}
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:nuevo }                                                                                                                                                           
    
brs_tur_configuracion:
    path:     /tur/configuracion/{codigoConfiguracionPk}
    defaults: { _controller: BrasaTurnoBundle:Configuracion:configuracion }    
    
brs_tur_validar_turno:
  pattern: /turno/validar/turno/{codigoProgramacionDetalle}/{dia}/{codigoTurno}
  defaults: { _controller: BrasaTurnoBundle:Validacion:turno }    