brs_tur_base_turno_lista:
    path:     /tur/base/turno/lista
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:lista }     
    
brs_tur_base_turno_detalle:
    path:     /tur/base/turno/detalle/{codigoTurno}
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:detalle }    
    
brs_tur_base_turno_nuevo:
    path:     /tur/base/turno/nuevo/{codigoTurno}
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:nuevo }

brs_tur_base_turno_detalle_nuevo:
   path:     /tur/base/turno/detalle/nuevo/{codigoTurno}/{codigoTurnoDetalle}
   defaults: { _controller: BrasaTurnoBundle:BaseTurno:detalleNuevo }

brs_tur_base_recurso_lista:
    path:     /tur/base/recurso/lista
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:lista }     
    
brs_tur_base_recurso_detalle:
    path:     /tur/base/recurso/detalle/{codigoRecurso}
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:detalle }    
    
brs_tur_base_recurso_nuevo:
    path:     /tur/base/recurso/nuevo/{codigoRecurso}/{codigoEmpleado}
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:nuevo }

brs_tur_base_recurso_nuevo_enlazar:
    path:     /tur/base/recurso/nuevo/enlazar/
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:enlazar } 

brs_tur_base_recurso_tipo_lista:
    path:     /tur/base/recurso/tipo/lista
    defaults: { _controller: BrasaTurnoBundle:BaseRecursoTipo:lista }           
    
brs_tur_base_recurso_tipo_nuevo:
    path:     /tur/base/recurso/tipo/nuevo/{codigoRecursoTipo}
    defaults: { _controller: BrasaTurnoBundle:BaseRecursoTipo:nuevo }

brs_tur_base_concepto_servicio_lista:
    path:     /tur/base/concepto/servicio/lista
    defaults: { _controller: BrasaTurnoBundle:BaseConceptoServicio:lista }          
    
brs_tur_base_concepto_servicio_nuevo:
    path:     /tur/base/concepto/servicio/nuevo/{codigoConceptoServicio}
    defaults: { _controller: BrasaTurnoBundle:BaseConceptoServicio:nuevo }               

brs_tur_base_prospecto_lista:
    path:     /tur/base/prospecto/lista
    defaults: { _controller: BrasaTurnoBundle:BaseProspecto:lista }            
    
brs_tur_base_prospecto_nuevo:
    path:     /tur/base/prospecto/nuevo/{codigoProspecto}
    defaults: { _controller: BrasaTurnoBundle:BaseProspecto:nuevo }

brs_tur_base_centro_costo_lista:
    path:     /tur/base/centro/costo/lista
    defaults: { _controller: BrasaTurnoBundle:BaseCentroCosto:lista }            
    
brs_tur_base_centro_costo_nuevo:
    path:     /tur/base/centro/costo/nuevo/{codigoCentroCosto}
    defaults: { _controller: BrasaTurnoBundle:BaseCentroCosto:nuevo }

brs_tur_base_plantilla_lista:
    path:     /tur/base/plantilla/lista
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:lista }     
    
brs_tur_base_plantilla_detalle:
    path:     /tur/base/plantilla/detalle/{codigoPlantilla}
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:detalle }    
    
brs_tur_base_plantilla_nuevo:
    path:     /tur/base/plantilla/nuevo/{codigoPlantilla}
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:nuevo }                                                                                                                                                

brs_tur_utilidad_programacion_inconsistencias:    
    path:     /tur/utilidad/programacion/inconsistencias
    defaults: { _controller: BrasaTurnoBundle:UtilidadProgramacionInconsistencia:lista }

brs_tur_utilidad_programacion_descarga_masiva:    
    path:     /tur/utilidad/programacion/descarga/masiva
    defaults: { _controller: BrasaTurnoBundle:UtilidadProgramacionDescargaMasiva:lista }            
    
brs_tur_configuracion:
    path:     /tur/configuracion/{codigoConfiguracionPk}
    defaults: { _controller: BrasaTurnoBundle:Configuracion:configuracion }    
    
brs_tur_validar_turno:
  pattern: /turno/validar/turno/{codigoProgramacionDetalle}/{dia}/{codigoTurno}
  defaults: { _controller: BrasaTurnoBundle:Validacion:turno }    