brs_tur_base_turno_lista:
    path:     /tur/base/turno/lista
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:lista }     
    
brs_tur_base_turno_detalle:
    path:     /tur/base/turno/detalle/{codigoTurno}
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:detalle }    
    
brs_tur_base_turno_nuevo:
    path:     /tur/base/turno/nuevo/{codigoTurno}
    defaults: { _controller: BrasaTurnoBundle:BaseTurno:nuevo }

brs_tur_base_turno_detalle_nuevo:
   path:     /tur/base/turno/detalle/nuevo/{codigoTurno}/{codigoTurnoDetalle}
   defaults: { _controller: BrasaTurnoBundle:BaseTurno:detalleNuevo }

brs_tur_base_recurso_lista:
    path:     /tur/base/recurso/lista
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:lista }     
    
brs_tur_base_recurso_detalle:
    path:     /tur/base/recurso/detalle/{codigoRecurso}
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:detalle }    
    
brs_tur_base_recurso_nuevo:
    path:     /tur/base/recurso/nuevo/{codigoRecurso}/{codigoEmpleado}
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:nuevo }

brs_tur_base_recurso_nuevo_enlazar:
    path:     /tur/base/recurso/nuevo/enlazar/
    defaults: { _controller: BrasaTurnoBundle:BaseRecurso:enlazar } 

brs_tur_base_recurso_tipo_lista:
    path:     /tur/base/recurso/tipo/lista
    defaults: { _controller: BrasaTurnoBundle:BaseRecursoTipo:lista }           
    
brs_tur_base_recurso_tipo_nuevo:
    path:     /tur/base/recurso/tipo/nuevo/{codigoRecursoTipo}
    defaults: { _controller: BrasaTurnoBundle:BaseRecursoTipo:nuevo }

brs_tur_base_concepto_servicio_lista:
    path:     /tur/base/concepto/servicio/lista
    defaults: { _controller: BrasaTurnoBundle:BaseConceptoServicio:lista }          
    
brs_tur_base_concepto_servicio_nuevo:
    path:     /tur/base/concepto/servicio/nuevo/{codigoConceptoServicio}
    defaults: { _controller: BrasaTurnoBundle:BaseConceptoServicio:nuevo }

brs_tur_base_cliente_lista:
    path:     /tur/base/cliente/lista
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:lista }     
    
brs_tur_base_cliente_detalle:
    path:     /tur/base/cliente/detalle/{codigoCliente}
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:detalle }    
    
brs_tur_base_cliente_nuevo:
    path:     /tur/base/cliente/nuevo/{codigoCliente}
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:nuevo }

brs_tur_base_cliente_puesto_nuevo:
    path:     /tur/base/cliente/puesto/nuevo/{codigoCliente}/{codigoPuesto}
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:puestoNuevo }    

brs_tur_base_cliente_direccion_nuevo:
    path:     /tur/base/cliente/direccion/nuevo/{codigoCliente}/{codigoDireccion}
    defaults: { _controller: BrasaTurnoBundle:BaseCliente:direccionNuevo } 

brs_tur_base_prospecto_lista:
    path:     /tur/base/prospecto/lista
    defaults: { _controller: BrasaTurnoBundle:BaseProspecto:lista }            
    
brs_tur_base_prospecto_nuevo:
    path:     /tur/base/prospecto/nuevo/{codigoProspecto}
    defaults: { _controller: BrasaTurnoBundle:BaseProspecto:nuevo }

brs_tur_base_centro_costo_lista:
    path:     /tur/base/centro/costo/lista
    defaults: { _controller: BrasaTurnoBundle:BaseCentroCosto:lista }            
    
brs_tur_base_centro_costo_nuevo:
    path:     /tur/base/centro/costo/nuevo/{codigoCentroCosto}
    defaults: { _controller: BrasaTurnoBundle:BaseCentroCosto:nuevo }

brs_tur_base_plantilla_lista:
    path:     /tur/base/plantilla/lista
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:lista }     
    
brs_tur_base_plantilla_detalle:
    path:     /tur/base/plantilla/detalle/{codigoPlantilla}
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:detalle }    
    
brs_tur_base_plantilla_nuevo:
    path:     /tur/base/plantilla/nuevo/{codigoPlantilla}
    defaults: { _controller: BrasaTurnoBundle:BasePlantilla:nuevo }
   
brs_tur_programacion_nuevo:
   path:     /tur/programacion/nuevo/{codigoProgramacion}
   defaults: { _controller: BrasaTurnoBundle:MovimientoProgramacion:nuevo }

brs_tur_programacion_detalle:
   path:     /tur/programacion/detalle/{codigoProgramacion}
   defaults: { _controller: BrasaTurnoBundle:MovimientoProgramacion:detalle }

brs_tur_programacion_detalle_nuevo:
   path:     /tur/programacion/detalle/nuevo/{codigoProgramacion}/{codigoProgramacionDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoProgramacion:detalleNuevo }      
   
brs_tur_programacion_detalle_nuevo_pedido:
   path:     /tur/programacion/detalle/nuevo/pedido/{codigoProgramacion}/{codigoProgramacionDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoProgramacion:detalleNuevoPedido }    
   
brs_tur_cotizacion_nuevo:
   path:     /tur/cotizacion/nuevo/{codigoCotizacion}
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:nuevo }

brs_tur_cotizacion_detalle:
   path:     /tur/cotizacion/detalle/{codigoCotizacion}
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:detalle }
   
brs_tur_cotizacion_detalle_nuevo:
   path:     /tur/cotizacion/detalle/nuevo/{codigoCotizacion}/{codigoCotizacionDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:detalleNuevo }    

brs_tur_cotizacion_otro_nuevo:
   path:     /tur/cotizacion/otro/nuevo/{codigoCotizacion}/{codigoCotizacionOtro}
   defaults: { _controller: BrasaTurnoBundle:MovimientoCotizacion:otroNuevo }         
   
brs_tur_pedido_nuevo:
   path:     /tur/pedido/nuevo/{codigoPedido}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:nuevo }

brs_tur_pedido_detalle:
   path:     /tur/pedido/detalle/{codigoPedido}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalle }
   
brs_tur_pedido_detalle_nuevo:
   path:     /tur/pedido/detalle/nuevo/{codigoPedido}/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalleNuevo }     
   
brs_tur_pedido_detalle_recurso:
   path:     /tur/pedido/detalle/recurso/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalleRecurso }    
   
brs_tur_pedido_detalle_recurso_nuevo:
   path:     /tur/pedido/detalle/recurso/nuevo/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalleRecursoNuevo }   
   
brs_tur_pedido_detalle_nuevo_cotizacion:
   path:     /tur/pedido/detalle/nuevo/cotizacion/{codigoPedido}/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalleNuevoCotizacion }   

brs_tur_pedido_detalle_nuevo_servicio:
   path:     /tur/pedido/detalle/nuevo/servicio/{codigoPedido}/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalleNuevoServicio } 

brs_tur_pedido_detalle_resumen:
   path:     /tur/pedido/detalle/resumen/{codigoPedidoDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoPedido:detalleResumen }
   
brs_tur_servicio_nuevo:
   path:     /tur/servicio/nuevo/{codigoServicio}
   defaults: { _controller: BrasaTurnoBundle:MovimientoServicio:nuevo }

brs_tur_servicio_detalle:
   path:     /tur/servicio/detalle/{codigoServicio}
   defaults: { _controller: BrasaTurnoBundle:MovimientoServicio:detalle }

brs_tur_servicio_detalle_recurso:
   path:     /tur/servicio/detalle/recurso/{codigoServicioDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoServicio:detalleRecurso }   

brs_tur_servicio_detalle_recurso_nuevo:
   path:     /tur/servicio/detalle/recurso/nuevo/{codigoServicioDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoServicio:detalleRecursoNuevo }    
   
brs_tur_servicio_detalle_nuevo:
   path:     /tur/servicio/detalle/nuevo/{codigoServicio}/{codigoServicioDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoServicio:detalleNuevo }     
   
brs_tur_servicio_detalle_nuevo_cotizacion:
   path:     /tur/servicio/detalle/nuevo/cotizacion/{codigoServicio}/{codigoServicioDetalle}
   defaults: { _controller: BrasaTurnoBundle:MovimientoServicio:detalleNuevoCotizacion }    
   
brs_tur_factura_nuevo:
   path:     /tur/factura/nuevo/{codigoFactura}
   defaults: { _controller: BrasaTurnoBundle:MovimientoFactura:nuevo }

brs_tur_factura_detalle:
   path:     /tur/factura/detalle/{codigoFactura}
   defaults: { _controller: BrasaTurnoBundle:MovimientoFactura:detalle }
   
brs_tur_factura_detalle_nuevo:
   path:     /tur/factura/detalle/nuevo/{codigoFactura}
   defaults: { _controller: BrasaTurnoBundle:MovimientoFactura:detalleNuevo }                                                  
    
brs_tur_proceso_generar_soporte_pago:
    path:     /tur/proceso/generar/soporte/pago
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarSoportePago:generar }
    
brs_tur_proceso_generar_soporte_pago_detalle:
    path:     /tur/proceso/generar/soporte/pago/detalle/{codigoSoportePagoPeriodo}
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarSoportePago:detalle }    

brs_tur_proceso_generar_soporte_pago_editar:
    path:     /tur/proceso/generar/soporte/pago/editar/{codigoSoportePago}
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarSoportePago:editar }    
    
brs_tur_proceso_generar_soporte_pago_detalle_ver:
    path:     /tur/proceso/generar/soporte/pago/detalle/ver/{codigoSoportePago}
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarSoportePago:ver }
    
brs_tur_proceso_generar_soporte_pago_nuevo:
    path:     /tur/proceso/generar/soporte/pago/nuevo/{codigoSoportePagoPeriodo}
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarSoportePago:nuevo }    
    
brs_tur_proceso_generar_programacion_lista:
    path:     /tur/proceso/generar/programacion/lista
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarProgramacion:lista }         
    
brs_tur_proceso_generar_pedido_lista:
    path:     /tur/proceso/generar/pedido/lista
    defaults: { _controller: BrasaTurnoBundle:ProcesoGenerarPedido:lista }                             

brs_tur_utilidad_programacion_inconsistencias:    
    path:     /tur/utilidad/programacion/inconsistencias
    defaults: { _controller: BrasaTurnoBundle:UtilidadProgramacionInconsistencia:lista }

brs_tur_utilidad_programacion_descarga_masiva:    
    path:     /tur/utilidad/programacion/descarga/masiva
    defaults: { _controller: BrasaTurnoBundle:UtilidadProgramacionDescargaMasiva:lista }    
    
brs_tur_buscar_cliente:
    pattern:  /tur/buscar/cliente/{campoCodigo}/{campoNombre}
    defaults: { _controller: BrasaTurnoBundle:BuscarCliente:lista }     
    
brs_tur_buscar_recurso:
    pattern:  /turno/buscar/recurso/{campoCodigo}/{campoNombre}
    defaults: { _controller: BrasaTurnoBundle:BuscarRecurso:buscar }    

brs_tur_buscar_recurso2:
    pattern:  /turno/buscar/recurso/{campoCodigo}
    defaults: { _controller: BrasaTurnoBundle:BuscarRecurso:buscar2 }
    
brs_tur_buscar_puesto:
    pattern:  /turno/buscar/puesto/{campoCodigo}/{codigoCliente}
    defaults: { _controller: BrasaTurnoBundle:BuscarPuesto:lista } 

brs_tur_buscar_direccion:
    pattern:  /turno/buscar/direccion/{campoCodigo}/{campoNombre}
    defaults: { _controller: BrasaTurnoBundle:BuscarDireccion:lista }    
    
brs_tur_configuracion:
    path:     /tur/configuracion/{codigoConfiguracionPk}
    defaults: { _controller: BrasaTurnoBundle:Configuracion:configuracion }    
    
brs_tur_validar_turno:
  pattern: /turno/validar/turno/{codigoProgramacionDetalle}/{dia}/{codigoTurno}
  defaults: { _controller: BrasaTurnoBundle:Validacion:turno }    